[package]
name = "image-subscriber"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["time"] }
time = "0.3"
zenoh = { version = "1.1.0"}